import Navigation from "../../components/navigation";

export const metadata = {
  title: "seoul_public_data",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Navigation />
        {children}
      </body>
    </html>
  );
}
